<a href="https://colab.research.google.com/github/Singko25/Linear-Algebra-58020/blob/main/FINAL_EXAM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###FINAL EXAM


##Problem 1

In [11]:
import numpy as np

A = np.array([[1,1,1], [1,0,4], [0,0,5]])
print(f'Matrix A: \n {A}')
print()

B = np.array([[89],[89],[95]])
print(f'Matrix B: \n {A}')

C = np.linalg.inv(A).dot(B)
print(f'Matrix A inverse: \n {C}')


Matrix A: 
 [[1 1 1]
 [1 0 4]
 [0 0 5]]

Matrix B: 
 [[1 1 1]
 [1 0 4]
 [0 0 5]]
Matrix A inverse: 
 [[13.]
 [57.]
 [19.]]


##Problem 2

In [12]:
import numpy as np

A = np.array([[3,-1,1],[9,3,-3],[-12,4,-4]])
print(f'Matrix A: \n {A}')

inv_A = np.linalg.pinv(A)
print(f'Matrix A inverse: \n {inv_A}')

B = np.array([[5],[10],[-20]])
print(f'Matrix A: \n {A}')

X = np.dot(inv_A,B)
print(f'Dot product: \n {X}')

C = np.dot(A,X)
print(f'Checking: \n {C}')


Matrix A: 
 [[  3  -1   1]
 [  9   3  -3]
 [-12   4  -4]]
Matrix A inverse: 
 [[ 0.00980392  0.05555556 -0.03921569]
 [-0.01470588  0.08333333  0.05882353]
 [ 0.01470588 -0.08333333 -0.05882353]]
Matrix A: 
 [[  3  -1   1]
 [  9   3  -3]
 [-12   4  -4]]
Dot product: 
 [[ 1.38888889]
 [-0.41666667]
 [ 0.41666667]]
Checking: 
 [[  5.]
 [ 10.]
 [-20.]]


##Problem 3

In [10]:
import numpy as np
from numpy.linalg import eig

A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print(A,"\n")
B,C = np.linalg.eig(A)

print("The eigenvalues: \n",B)
print("The eigenvectors: \n",C .round())

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]] 

The eigenvalues: 
 [-1.  3.  2.]
The eigenvectors: 
 [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
