<a href="https://colab.research.google.com/github/Singko25/Linear-Algebra-58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ##1. Create a Python code that displays a square matrix whose length is 5

In [4]:
import numpy as np
A = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[0,1,2,3,4]])
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [ 0  1  2  3  4]]


##2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero

In [7]:
import numpy as np 
A = np.array([[1,1,1,1],[0,1,1,1],[0,0,1,1],[0,0,0,1]])
print(A)

[[1 1 1 1]
 [0 1 1 1]
 [0 0 1 1]
 [0 0 0 1]]


##3.  Create a Python code that displays a square matrix which is symmetrical

In [ ]:
import numpy as np 
A = np.array([[]])

##4. What is the inverse of matrix C? Show your solution by python coding.

In [6]:
import numpy as np
A = np.array([[1,2,3],[2,3,3],[3,4,-2]])
Ans = (np.linalg.inv(A))
print(Ans)

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


##5.What is the determinant of the given matrix in Question 4? Show your solution by python coding.

In [8]:
import numpy as np
A = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(A)
print(np.linalg.det(A))
print(round(np.linalg.det(A)))


[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
5.000000000000001
5


##6. Find the roots of the linear equations by showing its python codes 

In [9]:
import numpy as np 
A = np.array([[5,4,1],[10,9,4],[10,13,15]])
Inv = np.linalg.inv(A)
print(A)
print(Inv)

B = np.array([[3.4],[8.8],[19.2]])

x = np.dot(Inv, B)
print("Roots: ", x)

z = np.dot(A, x)
print("Checking: ", z)

[[ 5  4  1]
 [10  9  4]
 [10 13 15]]
[[ 5.53333333 -3.13333333  0.46666667]
 [-7.33333333  4.33333333 -0.66666667]
 [ 2.66666667 -1.66666667  0.33333333]]
Roots:  [[0.2]
 [0.4]
 [0.8]]
Checking:  [[ 3.4]
 [ 8.8]
 [19.2]]
