<a href="https://colab.research.google.com/github/Singko25/Linear-Algebra-58020/blob/main/MIDTERMACT1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Python program that applies an inverse of 3x3 or 4x4 matrix 

In [12]:
import numpy as np
A = np.array([[4,-2,3],[9,1,1],[3,8,9]]) 
B = (np.linalg.inv(A))
print(B)

[[ 0.0027248   0.11444142 -0.01362398]
 [-0.21253406  0.07356948  0.0626703 ]
 [ 0.1880109  -0.10354223  0.0599455 ]]


In [11]:
A = np.array([[4,-2,3],[9,1,1],[3,8,9]])
print(A)
B = np.transpose(A)
print(B)

[[ 4 -2  3]
 [ 9  1  1]
 [ 3  8  9]]
[[ 4  9  3]
 [-2  1  8]
 [ 3  1  9]]


In [13]:
import numpy as np 
A = np.array([[4,-2,3,7],[9,1,1,2],[3,8,9,6],[8,9,3,4]])
B = (np.linalg.inv(A))
print(B)

[[-0.02903099  0.14476265  0.00156924 -0.02393095]
 [-0.02824637 -0.1023931  -0.0255002   0.13887799]
 [-0.09258533  0.16437819  0.1941938  -0.21145547]
 [ 0.19105532 -0.18242448 -0.0914084   0.14397803]]


In [14]:
A = np.array([[4,-2,3,7],[9,1,1,2],[3,8,9,6],[8,9,3,4]])
print(A)
B = np.transpose(A)
print(B)

[[ 4 -2  3  7]
 [ 9  1  1  2]
 [ 3  8  9  6]
 [ 8  9  3  4]]
[[ 4  9  3  8]
 [-2  1  8  9]
 [ 3  1  9  3]
 [ 7  2  6  4]]
