<a href="https://colab.research.google.com/github/Singko25/Linear-Algebra-58020/blob/main/PracticalLabExam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Practical Lab Exam 1
##John Louise M. Saavedra

##Problem 1

In [ ]:
#1) A
import numpy as np
W = np.array([[1, -3],[2,-2],[3,1]])
Y = np.array([[1, 2, 0],[0,-1,2]])

print(np.dot(W,Y))

[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]


In [ ]:
#1) B
Z = np.array([[0,1],[2,3]])
print(Z-Z)


[[0 0]
 [0 0]]


In [ ]:
#1) C
X = np.array([[3,2,1],[-1,2,3],[2,-1,1]])
multiply_array = 3*X

print(multiply_array)

[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]


##Problem 2


In [ ]:
#2) A
Y = np.array([[1, 2, 0],[0,-1,2]])
W = np.array([[1, -3],[2,-2],[3,1]])

print(np.dot(Y,W)^2)

[[ 7 -5]
 [ 6  6]]


In [ ]:
#2) B
import numpy as np
W = np.array([[1, -3],[2,-2],[3,1]])
print('Vector W is', W)

Vector W is [[ 1 -3]
 [ 2 -2]
 [ 3  1]]


In [ ]:
import numpy as np
Y = np.array([[1, 2, 0],[0,-1,2]])
print('Vector Y is', Y)

Vector Y is [[ 1  2  0]
 [ 0 -1  2]]


In [ ]:
import numpy as np
X = np.array([[3,2,1],[-1,2,3],[2,-1,1]])
print('Vector X is', X)


Vector X is [[ 3  2  1]
 [-1  2  3]
 [ 2 -1  1]]


In [ ]:

R = np.dot(W,Y)
print(R)

[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]


In [ ]:
print(np.subtract(R,X))
#2) B answer

[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]]


In [ ]:
#3) C
import numpy as np
W = np.array([[1, -3],[2,-2],[3,1]])
print('Vector W is', W)


In [ ]:
import numpy as np
Y = np.array([[1, 2, 0],[0,-1,2]])
print('Vector Y is', Y)

In [ ]:
import numpy as np 
Z = np.array([[0,1],[2,3]])
print('Vector Z is', Z)

In [ ]:
print("(YW - Z^2)")
print(np.dot(Y,W)-Z^2)

(YW - Z^2)
[[ 7 -6]
 [ 0  3]]
