<a href="https://colab.research.google.com/github/Singko25/Linear-Algebra-58020/blob/main/PRELIM_EXAM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##QUESTION 1

In [ ]:
import numpy as np 
C = np.eye(4)
print(C)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


##QUESTION 2

In [14]:
import numpy as np
C = np.eye(4)
print('C = ')
print(C)

array = np.multiply(2,C)
print('Doubled = ')
print(array)

C = 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Doubled = 
[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


##QUESTION 3


In [ ]:
import numpy as np 
A = np.array([2,7,4])
B = np.array([3,9,8])

cross = np.cross(A,B)
print(cross)

[20 -4 -3]
