<a href="https://colab.research.google.com/github/Singko25/Linear-Algebra-58020/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###MATRIX AND ITS OPERATIONS
SAAVEDRA, JOHN LOUISE M.

In [7]:
import numpy as np 
a = np.array([[-5,0],[4,1]])
print(a)
b = np.array([[6,-3],[2,3]])
print(b)

[[-5  0]
 [ 4  1]]
[[ 6 -3]
 [ 2  3]]


In [ ]:
a = np.array([[-5,0],[4,1]])
b = np.array([[6,-3],[2,3]])
print(a+b)

[[ 1 -3]
 [ 6  4]]


In [ ]:
a = np.array([[-5,0],[4,1]])
b = np.array([[6,-3],[2,3]])
print(a-b)

[[-11   3]
 [  2  -2]]


In [ ]:
b = np.array([[6,-3],[2,3]])
print(b-b)

[[0 0]
 [0 0]]
