<a href="https://colab.research.google.com/github/Singko25/Linear-Algebra-58020/blob/main/Python_Exercise3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
A = np.array([[1,1,1],[1,2,2],[1,2,3]])
print(A)
inv_A=np.linalg.inv(A)
print(inv_A)
B = np.array([[5],[6],[8]])
print(B)
X = np.dot(inv_A,B)
print(X)

[[1 1 1]
 [1 2 2]
 [1 2 3]]
[[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  1.]]
[[5]
 [6]
 [8]]
[[ 4.]
 [-1.]
 [ 2.]]
