<a href="https://colab.research.google.com/github/Singko25/Linear-Algebra-58020/blob/main/Python_Exercise2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Vector Space Operations

In [1]:
import numpy as np
A = np.array([4,3])
B = np.array([2,-5])

print("Vector A is" , A)
print("Vector B is" , B)

Vector A is [4 3]
Vector B is [ 2 -5]


In [2]:
ball1 = np.array([[1,2,3]])
ball2 = np.array([[1,2,3]])
pool = np.array([ball1,ball2])
pool.shape
pool.size
print(pool.shape)
print(pool.size)

(2, 1, 3)
6


In [3]:
R = A+B
print(R)

[ 6 -2]


In [4]:
R = np.add(A,B)
R

array([ 6, -2])

In [10]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
sum = addend1 + addend2
sum

array([1, 1, 0])

In [5]:
R = np.subtract(A,B)
R

array([2, 8])

In [6]:
A = np.array([1,5,8,9])
S = 5*A
print(S)
#vector scaling

[ 5 25 40 45]


In [7]:
S = np.multiply(5,A)
print(S)

[ 5 25 40 45]


In [8]:
#initialize arrays
A = np.array([2,3,4])
B = np.array([1,7,0])

#compute cross product
output = np.cross(A,B)
print(output)


[-28   4  11]


In [11]:
A = np.array([2,7])
B = np.array([1,7])

output = np.cross(A,B)
print(output)

7


In [9]:
output = np.dot(A,B) 
#compute the product dot of A and B
print(output)


23
