<a href="https://colab.research.google.com/github/Singko25/Linear-Algebra-58020/blob/main/SAAVEDRA_VECTOR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix And Its Operations


In [ ]:
import numpy as nmp
#Create a 1x3 array
a = nmp.array([1,2,3])
print(a)


[1 2 3]


In [5]:
b = nmp.array([[1,2,3],[-1,-2,-3]])
print(b)

[[ 1  2  3]
 [-1 -2 -3]]


In [7]:
c = nmp.array([[1,2,3],[-1,-2,-3],[4,5,6]])
print(c)

[[ 1  2  3]
 [-1 -2 -3]
 [ 4  5  6]]


In [8]:
d = nmp.array([[1,2,3],[-1,-2,-3],[4,5,6]])
print(d)
e = nmp.diagonal([[1,2,3],[-1,-2,-3],[4,5,6]])
print(e)
#diagonal

[[ 1  2  3]
 [-1 -2 -3]
 [ 4  5  6]]
[ 1 -2  6]


In [10]:
f = nmp.eye(3)
print(f)
#identity

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
g = nmp.zeros((8,3))
print(g)
#zero

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
h = nmp.empty((0,5))
print(h)
#empty

[]


In [17]:
#matrix addition
i = nmp.array([[1,2,3],[-1,-2,-3]])
j = nmp.array([[3,4,5],[-3,-4,-5]])
print(j+i)

[[ 4  6  8]
 [-4 -6 -8]]


In [18]:
#substraction
k = nmp.array([[1,2,3],[-1,-2,-3]])
l = nmp.array([[3,4,5],[-3,-4,-5]])
print(k-l)

[[-2 -2 -2]
 [ 2  2  2]]
